name: urdu_quiz_app
description: 3000 Urdu Quiz Flutter Game with RTL and Nastaliq Font support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  google_mobile_ads: ^5.0.0
  share_plus: ^9.0.0
  csv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/quiz_data_3000.json
    - assets/Final_UrduQuiz_3000.csv
    - assets/images/Gemini_Generated_Image_drolzqdrolzqdrol.png
    - assets/images/Gemini_Generated_Image_sdqol1sdqol1sdqo.png

  fonts:
    - family: UrduNastaliq
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-VariableFont_wght.ttf
